### ISSUE TITLE
mpp-branch - gradle-0.5-plugin not found

### ISSUE THREAD

**Issue by freiit** [jwstegemann/fritz2-template#1]
Might not be worth a ticket, but I was playing around with the mpp branch and get this:

A problem occurred configuring root project 'fritz2-template'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find io.fritz2:fritz2-gradle-plugin:0.5.
     Searched in the following locations:
       - file:/home/.../.m2/repository/io/fritz2/fritz2-gradle-plugin/0.5/fritz2-gradle-plugin-0.5.pom
       - https://jcenter.bintray.com/io/fritz2/fritz2-gradle-plugin/0.5/fritz2-gradle-plugin-0.5.pom
       - https://plugins.gradle.org/m2/io/fritz2/fritz2-gradle-plugin/0.5/fritz2-gradle-plugin-0.5.pom
     Required by:
         project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html

Anyways - keep going - I like what you are doing here :-)

**Comment by jamowei** [comment]
Thanks! We had sich branch for converting to Kotlin multi platform project setup. We have release this feature with our new 0.6 version of fritz2. So this out of date anymore ;-)
If you find some trouble with the 0.6 release please let us know! :-)
